
package com.roma.elettorale.modelli3D.entity.anagrafe;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IntegrationSmartSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IntegrationSmartSoap {


    /**
     * 
     * @param callMapperWebMethodResult
     * @param remotHost
     * @param logon
     * @param servizio
     * @param tpurcode
     * @param mapperes
     * @param dept
     * @param pwd
     * @param env
     * @param serviceName
     * @param dati
     */
    @WebMethod(operationName = "CallMapperWebMethod", action = "http://tempuri.org/CallMapperWebMethod")
    @RequestWrapper(localName = "CallMapperWebMethod", targetNamespace = "http://tempuri.org/", className = "com.roma.elettorale.fascicoli.entity.anagrafe.CallMapperWebMethod")
    @ResponseWrapper(localName = "CallMapperWebMethodResponse", targetNamespace = "http://tempuri.org/", className = "com.roma.elettorale.fascicoli.entity.anagrafe.CallMapperWebMethodResponse")
    public void callMapperWebMethod(
        @WebParam(name = "Logon", targetNamespace = "http://tempuri.org/")
        String logon,
        @WebParam(name = "Dept", targetNamespace = "http://tempuri.org/")
        String dept,
        @WebParam(name = "PWD", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "Servizio", targetNamespace = "http://tempuri.org/")
        String servizio,
        @WebParam(name = "Env", targetNamespace = "http://tempuri.org/")
        String env,
        @WebParam(name = "MAPPERES", targetNamespace = "http://tempuri.org/")
        String mapperes,
        @WebParam(name = "RemotHost", targetNamespace = "http://tempuri.org/")
        String remotHost,
        @WebParam(name = "ServiceName", targetNamespace = "http://tempuri.org/")
        String serviceName,
        @WebParam(name = "CallMapperWebMethodResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Boolean> callMapperWebMethodResult,
        @WebParam(name = "Dati", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> dati,
        @WebParam(name = "TPURCODE", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Integer> tpurcode);

}
