
package com.roma.elettorale.modelli3D.entity.anagrafe;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IntegrationSmart", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/C:/Users/Nick/Documents/javaprojects/ElezioniIdeaProject/fascicoli/src/main/resources/wsdl/opentiws.wsdl")
public class IntegrationSmart
    extends Service
{

    private final static URL INTEGRATIONSMART_WSDL_LOCATION;
    private final static WebServiceException INTEGRATIONSMART_EXCEPTION;
    private final static QName INTEGRATIONSMART_QNAME = new QName("http://tempuri.org/", "IntegrationSmart");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
          //  url = new URL("file:/C:/Users/Nick/Documents/javaprojects/ElezioniIdeaProject/fascicoli/src/main/resources/wsdl/opentiws.wsdl");
            url = new URL("file:/C:/Users/AdminDSI/IdeaProjects/fascicoli/src/main/resources/wsdl/opentiws.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INTEGRATIONSMART_WSDL_LOCATION = url;
        INTEGRATIONSMART_EXCEPTION = e;
    }

    public IntegrationSmart() {
        super(__getWsdlLocation(), INTEGRATIONSMART_QNAME);
    }

    public IntegrationSmart(WebServiceFeature... features) {
        super(__getWsdlLocation(), INTEGRATIONSMART_QNAME, features);
    }

    public IntegrationSmart(URL wsdlLocation) {
        super(wsdlLocation, INTEGRATIONSMART_QNAME);
    }

    public IntegrationSmart(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INTEGRATIONSMART_QNAME, features);
    }

    public IntegrationSmart(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntegrationSmart(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IntegrationSmartSoap
     */
    @WebEndpoint(name = "IntegrationSmartSoap")
    public IntegrationSmartSoap getIntegrationSmartSoap() {
        return super.getPort(new QName("http://tempuri.org/", "IntegrationSmartSoap"), IntegrationSmartSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IntegrationSmartSoap
     */
    @WebEndpoint(name = "IntegrationSmartSoap")
    public IntegrationSmartSoap getIntegrationSmartSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "IntegrationSmartSoap"), IntegrationSmartSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INTEGRATIONSMART_EXCEPTION!= null) {
            throw INTEGRATIONSMART_EXCEPTION;
        }
        return INTEGRATIONSMART_WSDL_LOCATION;
    }

}
