
package com.roma.elettorale.modelli3D.entity.unidoc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ControllerOperazioniWS", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/C:/Users/Nick/Documents/javaprojects/ElezioniIdeaProject/modelli3D/src/main/resources/wsdl/unidocwsdl.wsdl")
public class ControllerOperazioniWS
    extends Service
{

    private final static URL CONTROLLEROPERAZIONIWS_WSDL_LOCATION;
    private final static WebServiceException CONTROLLEROPERAZIONIWS_EXCEPTION;
    private final static QName CONTROLLEROPERAZIONIWS_QNAME = new QName("http://tempuri.org/", "ControllerOperazioniWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
           //  url = new URL("file:/C:/Users/Nick/Documents/javaprojects/ElezioniIdeaProject/modelli3D/src/main/resources/wsdl/unidocwsdl.wsdl");
            url = new URL("file:/C:/Users/AdminDSI/IdeaProjects/modelli3D/src/main/resources/wsdl/unidocwsdl.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTROLLEROPERAZIONIWS_WSDL_LOCATION = url;
        CONTROLLEROPERAZIONIWS_EXCEPTION = e;
    }

    public ControllerOperazioniWS() {
        super(__getWsdlLocation(), CONTROLLEROPERAZIONIWS_QNAME);
    }

    public ControllerOperazioniWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTROLLEROPERAZIONIWS_QNAME, features);
    }

    public ControllerOperazioniWS(URL wsdlLocation) {
        super(wsdlLocation, CONTROLLEROPERAZIONIWS_QNAME);
    }

    public ControllerOperazioniWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTROLLEROPERAZIONIWS_QNAME, features);
    }

    public ControllerOperazioniWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControllerOperazioniWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ControllerOperazioniWSSoap
     */
    @WebEndpoint(name = "ControllerOperazioniWSSoap")
    public ControllerOperazioniWSSoap getControllerOperazioniWSSoap() {
        return super.getPort(new QName("http://tempuri.org/", "ControllerOperazioniWSSoap"), ControllerOperazioniWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControllerOperazioniWSSoap
     */
    @WebEndpoint(name = "ControllerOperazioniWSSoap")
    public ControllerOperazioniWSSoap getControllerOperazioniWSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ControllerOperazioniWSSoap"), ControllerOperazioniWSSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTROLLEROPERAZIONIWS_EXCEPTION!= null) {
            throw CONTROLLEROPERAZIONIWS_EXCEPTION;
        }
        return CONTROLLEROPERAZIONIWS_WSDL_LOCATION;
    }

}
